name: 07 - Using Expressions practice
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
    branches:
      main
jobs:
  eho:
    runs-on: ubuntu-latest
    steps:
      - name: [debug] Print start-up data
        if: inputs.debug
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
      - name: [debug] Print when triggered from main
        if: inputs.debug
        run: echo "I was triggered from main"
      - name: Greeting
        run: echo "Hello, world"


